/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customers */
        get: operations["customers_api_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer */
        get: operations["customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/sources/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Source */
        get: operations["source_api_customers__customer_id__sources__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/interactions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview
         * @description Parse / transcribe an upload into Interactions for the salesperson to check. Writes nothing to memory.
         */
        post: operations["preview_api_customers__customer_id__interactions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description Extract + remember in both banks. Runs inside this request (Vercel functions stop when they respond);
         *     the job record keeps the result so the UI can re-read it.
         */
        post: operations["ingest_api_customers__customer_id__interactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompt-pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prompt Pieces
         * @description The injectable prompt pieces the executive can add to a request (memory_agent/prompts.py).
         */
        get: operations["prompt_pieces_api_prompt_pieces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_api_customers__customer_id__requests_get"];
        put?: never;
        /** Create Request */
        post: operations["create_request_api_customers__customer_id__requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_api_customers__customer_id__requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Profile
         * @description Cached on the customer record; any new interaction clears the cache.
         */
        get: operations["profile_api_customers__customer_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Company Insights */
        get: operations["company_insights_api_company_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        /**
         * Save Settings
         * @description Admins edit the org's main prompt. Saving the default text again is the same as a reset.
         */
        post: operations["save_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign */
        post: operations["assign_api_users__user_id__customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignIn */
        AssignIn: {
            /** Customer Ids */
            customer_ids: string[];
        };
        /** Body_preview_api_customers__customer_id__interactions_preview_post */
        Body_preview_api_customers__customer_id__interactions_preview_post: {
            /** Text */
            text?: string | null;
            /** File */
            file?: string | null;
            /** Recording Url */
            recording_url?: string | null;
            /** Channel */
            channel?: string | null;
            /** Title */
            title?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /** Participants */
            participants?: string | null;
        };
        /**
         * CallPlan
         * @description The call in order. Each step is a separate field, so the order is guaranteed by the schema.
         */
        CallPlan: {
            opening: components["schemas"]["ScriptStep"];
            recap: components["schemas"]["ScriptStep"];
            discovery: components["schemas"]["ScriptStep"];
            value: components["schemas"]["ScriptStep"];
            objections: components["schemas"]["ScriptStep"];
            close: components["schemas"]["ScriptStep"];
        };
        /** Cited */
        Cited: {
            /** Text */
            text: string;
            /**
             * Sources
             * @description Source ids from memory, e.g. CALL-03, EM-02, or INS-… for company lessons
             */
            sources: string[];
        };
        /** CustomerDetail */
        CustomerDetail: {
            customer: components["schemas"]["CustomerOut"];
            /** Interactions */
            interactions: components["schemas"]["SourceRow"][];
        };
        /** CustomerIn */
        CustomerIn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Industry */
            industry: string;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Industry */
            industry: string;
            /** Bank Id */
            bank_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "creating" | "active";
            /** Owner User Id */
            owner_user_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestIn */
        IngestIn: {
            /** Interactions */
            interactions: components["schemas"]["Interaction"][];
            /** Request Id */
            request_id?: string | null;
        };
        /** IngestResult */
        IngestResult: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Remembered */
            remembered: string[];
            /** Company Insights */
            company_insights: string[];
            /**
             * Rejected Insights
             * @default 0
             */
            rejected_insights: number;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Next Steps
             * @default []
             */
            next_steps: string[];
            /**
             * Extraction Ok
             * @default true
             */
            extraction_ok: boolean;
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceStep"][];
        };
        /** Insight */
        Insight: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Text */
            text: string;
            /** Industry */
            industry?: string | null;
            /** Role */
            role?: string | null;
            /**
             * Evidence
             * @default observed_once
             */
            evidence: string;
            /**
             * Occurred At
             * @default
             */
            occurred_at: string;
        };
        /** Interaction */
        Interaction: {
            /** Document Id */
            document_id: string;
            /**
             * Channel
             * @enum {string}
             */
            channel: "call" | "email" | "whatsapp" | "crm" | "note" | "document" | "outcome";
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Title */
            title: string;
            /**
             * Participants
             * @default []
             */
            participants: components["schemas"]["Participant"][];
            /**
             * Turns
             * @default []
             */
            turns: components["schemas"]["Turn"][];
            /** Text */
            text: string;
            /**
             * Source Ref
             * @default
             */
            source_ref: string;
            /**
             * Fingerprints
             * @default []
             */
            fingerprints: string[];
            /**
             * Mode
             * @default replace
             * @enum {string}
             */
            mode: "replace" | "append";
            /** Request Id */
            request_id?: string | null;
        };
        /** InteractionPreview */
        InteractionPreview: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Interactions */
            interactions: components["schemas"]["Interaction"][];
            /**
             * Detected Channel
             * @enum {string}
             */
            detected_channel: "call" | "email" | "whatsapp" | "crm" | "note" | "document" | "outcome";
            /**
             * New Fingerprints
             * @default 0
             */
            new_fingerprints: number;
            /**
             * Duplicate Fingerprints
             * @default 0
             */
            duplicate_fingerprints: number;
            /**
             * Unknown Names
             * @default []
             */
            unknown_names: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceStep"][];
        };
        /** JobOut */
        JobOut: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            /** Stage */
            stage: string;
            result?: components["schemas"]["IngestResult"] | null;
            /** Error */
            error?: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Token */
            token: string;
            user: components["schemas"]["UserOut"];
        };
        /** ObjectionPlay */
        ObjectionPlay: {
            /** Objection */
            objection: string;
            /** Raised By */
            raised_by: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
            /**
             * Response
             * @description What to say back, first person, natural spoken words
             */
            response: string;
            /** Sources */
            sources: string[];
        };
        /** OpenItem */
        OpenItem: {
            /** Text */
            text: string;
            /**
             * Owner
             * @description Who must act: our salesperson or a named customer person
             */
            owner: string | null;
            /**
             * Due
             * @description Due date as YYYY-MM-DD when memory gives one, else null
             */
            due: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "overdue" | "at_risk";
            /** Sources */
            sources: string[];
        };
        /** OrgSettings */
        OrgSettings: {
            /** Main Prompt */
            main_prompt: string;
            /** Default Prompt */
            default_prompt: string;
            /** Is Default */
            is_default: boolean;
            /** Locked Rules */
            locked_rules: string;
            /** Placeholders */
            placeholders: string[];
            /** Updated By */
            updated_by?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** OrgSettingsIn */
        OrgSettingsIn: {
            /** Main Prompt */
            main_prompt: string;
        };
        /** Participant */
        Participant: {
            /** Name */
            name: string;
            /**
             * Side
             * @default customer
             * @enum {string}
             */
            side: "ours" | "customer" | "unknown";
            /**
             * Role
             * @default
             */
            role: string;
        };
        /** Profile */
        Profile: {
            /** Pain Points */
            pain_points: components["schemas"]["ProfileItem"][];
            /** Goals */
            goals: components["schemas"]["ProfileItem"][];
            /** Objections */
            objections: components["schemas"]["ProfileItem"][];
            /** Stakeholders */
            stakeholders: components["schemas"]["ProfileItem"][];
            /** Competitors */
            competitors: components["schemas"]["ProfileItem"][];
            /** Requirements */
            requirements: components["schemas"]["ProfileItem"][];
            /** Commitments */
            commitments: components["schemas"]["ProfileItem"][];
            /** Pricing */
            pricing: components["schemas"]["ProfileItem"][];
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
        };
        /** ProfileItem */
        ProfileItem: {
            /**
             * Text
             * @description The fact, one sentence
             */
            text: string;
            /**
             * Detail
             * @description At most 8 words of extra context (who raised it, role, status or due date). Never repeat `text`. null when there is nothing to add
             */
            detail: string | null;
            /** Sources */
            sources: string[];
        };
        /** PromptPiece */
        PromptPiece: {
            /** Id */
            id: string;
            /**
             * Group
             * @enum {string}
             */
            group: "call_type" | "focus";
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** Report */
        Report: {
            /**
             * Answer
             * @description Direct answer to the salesperson's question, under 120 words
             */
            answer: string;
            /**
             * Summary
             * @description Where the deal stands, 2 sentences
             */
            summary: string;
            /**
             * Deal Stage
             * @enum {string}
             */
            deal_stage: "discovery" | "evaluation" | "negotiation" | "closing" | "won" | "lost";
            /**
             * Deal Health
             * @enum {string}
             */
            deal_health: "on_track" | "at_risk" | "off_track";
            /**
             * Health Reason
             * @description One short sentence: the main reason for the health rating
             */
            health_reason: string;
            /** What To Ask */
            what_to_ask: components["schemas"]["Cited"][];
            /** Open Items */
            open_items: components["schemas"]["OpenItem"][];
            /** Stakeholders */
            stakeholders: components["schemas"]["StakeholderPlay"][];
            /** Objections */
            objections: components["schemas"]["ObjectionPlay"][];
            /** Risks */
            risks: components["schemas"]["Cited"][];
            /** Playbook Tips */
            playbook_tips: components["schemas"]["Cited"][];
            call_plan: components["schemas"]["CallPlan"];
            /** Next Steps */
            next_steps: string[];
            /** Follow Up Email */
            follow_up_email: string;
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /**
             * Memory Used
             * @default {}
             */
            memory_used: {
                [key: string]: number;
            };
            /**
             * Pieces
             * @default []
             */
            pieces: string[];
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
            /**
             * Trace
             * @default []
             */
            trace: components["schemas"]["TraceStep"][];
        };
        /** RequestIn */
        RequestIn: {
            /** Prompt */
            prompt: string;
            /**
             * Pieces
             * @default []
             */
            pieces: string[];
            /** Parent Request Id */
            parent_request_id?: string | null;
        };
        /** RequestOut */
        RequestOut: {
            /** Request Id */
            request_id: string;
            /** Customer Id */
            customer_id: string;
            /** Prompt */
            prompt: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            report: components["schemas"]["Report"];
        };
        /** RequestRow */
        RequestRow: {
            /** Request Id */
            request_id: string;
            /** Prompt */
            prompt: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Summary */
            summary: string;
        };
        /** ScriptStep */
        ScriptStep: {
            /**
             * Say
             * @description What to say at this step, first person, natural spoken words
             */
            say: string;
            /** Sources */
            sources: string[];
        };
        /** SourceRow */
        SourceRow: {
            /** Document Id */
            document_id: string;
            /** Channel */
            channel: string;
            /** Title */
            title: string;
            /** Occurred At */
            occurred_at: string;
            /** People */
            people?: string | null;
            /** Memories */
            memories?: number | null;
        };
        /** SourceText */
        SourceText: {
            /** Document Id */
            document_id: string;
            /** Text */
            text: string;
        };
        /** StakeholderPlay */
        StakeholderPlay: {
            /** Name */
            name: string;
            /** Role */
            role: string | null;
            /**
             * Stance
             * @description Where this person stands on the deal right now, from what memory shows
             * @enum {string}
             */
            stance: "champion" | "supporter" | "neutral" | "skeptic" | "blocker";
            /** Cares About */
            cares_about: string;
            /** How To Win */
            how_to_win: string;
            /** Sources */
            sources: string[];
        };
        /** TraceStep */
        TraceStep: {
            /** Step */
            step: string;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Result
             * @default
             */
            result: string;
        };
        /** Turn */
        Turn: {
            /** Speaker */
            speaker: string;
            /**
             * Side
             * @default unknown
             * @enum {string}
             */
            side: "ours" | "customer" | "unknown";
            /** Text */
            text: string;
            /**
             * At
             * @default
             */
            at: string;
            /**
             * Speaker Inferred
             * @default false
             */
            speaker_inferred: boolean;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "sales_exec" | "admin";
            /** Customer Ids */
            customer_ids: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customers_api_customers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_customers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_api_customers__customer_id__sources__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_customers__customer_id__interactions_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_api_customers__customer_id__interactions_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_api_customers__customer_id__interactions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompt_pieces_api_prompt_pieces_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPiece"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_api_customers__customer_id__requests_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_api_customers__customer_id__requests_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_api_customers__customer_id__requests__request_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_api_customers__customer_id__profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_insights_api_company_insights_get: {
        parameters: {
            query?: {
                industry?: string | null;
                role?: string | null;
                kind?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Insight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_api_users__user_id__customers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
